FROM python:3.9-slim

RUN pip install azure-ai-textanalytics

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

ENV FLASK_APP=web.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=8080"]
